# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: 78548955-63ff-45c9-907c-539da38a4bcc
          MESSAGE: "Hey Tara Ram Mohan, there's a new build!".